### ISSUE TITLE
Replace eigentrust++ with new reputation handling

### ISSUE THREAD

**Issue by kaiyzen** [nemtech/catapult-server#12]
In nis1 eigentrust++ implementation is used for reputation of nodes trusted within the network.  A new/different implementation is being worked on for catapult, more details and documentation to follow as the design is finalized and implemented.

**Comment by Jaguar0625** [comment]
each node will gather data when interacting with other nodes. If a connect to a remote node succeeds the success counter is incremented, otherwise the failure counter is incremented. Also after  the data received from the remote node has been processed, the result (data was valid and could be used or data was invalid for some reason and thus was unusable) is used to increment the success / failure counter.

From that interaction stats a weight is assigned to the remote node (weight is between 500 and 10000). When a remote is selected the probability for selecting a remote depends linearly on the weight it has. Every 4 rounds the selection of a remote node is done according to the importance of the node. This guarantees that even in case we are facing a sybil attack every 4 rounds a node with high importance (and thus hopefully a trustworthy node) is selected.

**Comment by Jaguar0625** [comment]
8467be1485db44d60a9704ddf2eeab9050273911
