### ISSUE TITLE
State Change Receipt Capabilities

### ISSUE THREAD

**Issue by kaiyzen** [nemtech/catapult-server#18]
Certain state changes are invisible and/or time-delayed and not triggered by any immediately observable catalyst:

* Namespace expiration (triggering a cascade of expiring mosaics)
* Lock expiration (causing fee payment to harvester or to lock owner)
* Levy transfers (especially percentage-based levies that require knowledge of current mosaic state)

The primary goal of this feature is to make dependent state changes visible in the block where they take effect.

**Comment by gimer** [comment]
Server part is done, when it comes to namespaces and locks via receipts/statements.
Levy is not there yet and not planned for dragon

**Comment by kaiyzen** [comment]
we can break out the levy receipt item into another enhancement and assign to "E" for now, pushing out if needed depending on where scheduling/priorities fall

**Comment by Jaguar0625** [comment]
BlockReceiptsHash is set to a non-zero value when a block triggers “invisible” state changes. An invisible state change is any change that is not observable directly from block header and/or transaction data, but, instead, is state-dependent. For example, the changes caused by any transaction referencing aliases is unknowable without knowing the current alias state at the time of execution.

Importantly, receipts allow a client to perform the following so that all state changes are fully explained in a cryptographically secure way:
*apply(State(H), Block(H), Receipts(H)) => State(H+1)*

Receipts are produced by observers in a deterministic order and hashed into a merkle tree. The merkle tree root hash is stored in the block header.

Catapult can generate three types of receipts:
1. State Change Receipt: A receipt that informs a client about a state change
 a. Balance Transfer: A mosaic transfer was triggered
 b. Balance Change: A mosaic credit or debit was triggered
 c. Artifact Expiry: An artifact (e.g. namespace) expired
2. Account Alias: An account alias was used in the block
3. Mosaic Alias: A mosaic alias was used in the block

Alias receipts record the first occurence of an (unresolved, resolved) alias pair used in a block.

**Comment by Jaguar0625** [comment]
8467be1485db44d60a9704ddf2eeab9050273911
