### ISSUE TITLE
lightning network support

### ISSUE THREAD

**Issue by Jaguar0625** [nemtech/catapult-server#25]
placeholder issue for a handful of enhancements to allow lightning networks to be built on catapult

details to follow

**Comment by jabo38** [comment]
It seems like Bitcoin uses CLTV time lock txs and OP_CSV time locks in Lightning. But these are specific to UTXO txs.  https://prestwi.ch/bitcoin-time-locks/  Since we are an account based system, I'll look into Ethereum's Raidon network for similarities. 

I'll also ask Yuki to look into this more.  https://github.com/planethouki/bidirectional-nem2-payment-channel-sample

**Comment by gimer** [comment]
@jabo38 any news on Raiden?

**Comment by jabo38** [comment]
Generally, they are the same theory of how to open and close payment channels but how they are maintained and updated off-chain is a bit different. 

Bitcoin's Lightning network will be more privacy centered and thus a bit harder to implement and more expensive for those operating and watching the network to ensure there is no cheating. 

Raiden will not have as good privacy but will be more focused on business use cases and will be cheaper to maintain. 

There is a TL:DR at the bottom of this article as well as an in-depth explanation throughout it. https://medium.com/crypto-punks/lightning-vs-raiden-watchtowers-monitoring-services-differences-c8eb0f724e68

Generally, given our target audience, I'm more inclined to lean towards the Raiden implementation for inspiration.

**Comment by gimer** [comment]
Besides #28, nothing more is needed now, closing this one, and new issues should be created if there's need for additional features
