### ISSUE TITLE
v0964-beta1 Sync speed decreases as block height increases

### ISSUE THREAD

**Issue by dusanjp** [nemtech/catapult-server#86]
The synchronization speed of the node just launched is fast
But
Sync speed becomes extremely slow from around 200,000 blocks

If you restart a node that has stopped synchronizing, the synchronization will stop halfway.

The newly built 8GB and 16GB nodes have successfully reached the topblock,
From this, it is assumed that the amount of memory does not matter

The node that has been running until then and stopped for some reason,
Often unable to reach topblock

When the height of the block rises,
Nodes that are built late are
It will take a long time to reach the top block

**Comment by gimer** [comment]
Assuming here this happens on api/dual node.

The issue is due to large value (>1000) of `maxBlocksPerSyncAttempt`.

In network with finalization enabled, this value can be kept low (~50)

In network with finalization disabled, the value can be lowered as well, the setting affects sync speed, and the choice should be balance between amount of blocks downloaded in one batch and avail memory.

Part of the problem is mongo consuming large amount of memory with large values of `maxBlocksPerSyncAttempt`. Mongo memory might be capped and that is what bootstrap is currently doing.
